package lsc.bean.resume;

import java.io.Serializable;
import java.util.Date;

public class Talent implements Serializable {
    private Long id;

    private Integer gender;

    private Integer anualSalary;

    private Date updateTime;

    private Long addUserId;

    private String rank;

    private Date addTime;

    private String comment;

    private String email;

    private String phone;

    private String name;

    private String jobTitle;

    private Integer birthYear;

    private Integer graduateYear;

    private Short degreeId;

    private Long cityId;

    private Integer deleted;

    private Integer status;

    private Integer level;

    private String birthday;

    private Integer maritalStatus;

    private String idCard;

    private String address;

    private Integer expectAnnualSalary;

    private String avatar;

    private String englishName;

    private Long updateUserId;

    private String city;

    private Long resumeId;

    private String expectCity;

    private Integer standardized;

    private Long defaultRecommandReportId;

    private Long postRecommandReportId;

    private String selfEvaluation;

    private String salaryDesc;

    private Integer currentSalary;

    private Float currentSalaryMonths;

    private Integer expectSalary;

    private Integer expectSalaryMonths;

    private String otherWelfare;

    private String extraMsg;

    private Integer applyJobStatus;

    private String expectIndustry;

    private String expectFunction;

    private Integer openStatus;

    private Long companyId;

    private Long createUserId;

    private Integer oldOpenStatus;

    private Long hhCategoryId;

    private Integer startWorkYear;

    private Integer integrity;

    private String expectAnnualSalaryDesc;

    private String expectPositionTitles;

    private Integer defaultResumeType;

    private Long cvId;

    private String companyName;

    private String school;

    private Long jobhunterId;

    private String otherRequire;

    private Integer salaryType;

    private Integer coverByJobhunter;

    private Date jobhunterUpdateTime;

    private String expertTagContent;

    private String competentTagContent;

    private String outsideTalentId;

    private Integer source;

    private Integer contactPeriod;

    private Integer expectSalaryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hd_talent
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.id
     *
     * @return the value of hd_talent.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.id
     *
     * @param id the value for hd_talent.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.gender
     *
     * @return the value of hd_talent.gender
     *
     * @mbggenerated
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.gender
     *
     * @param gender the value for hd_talent.gender
     *
     * @mbggenerated
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.anualSalary
     *
     * @return the value of hd_talent.anualSalary
     *
     * @mbggenerated
     */
    public Integer getAnualSalary() {
        return anualSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.anualSalary
     *
     * @param anualSalary the value for hd_talent.anualSalary
     *
     * @mbggenerated
     */
    public void setAnualSalary(Integer anualSalary) {
        this.anualSalary = anualSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.updateTime
     *
     * @return the value of hd_talent.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.updateTime
     *
     * @param updateTime the value for hd_talent.updateTime
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.addUserId
     *
     * @return the value of hd_talent.addUserId
     *
     * @mbggenerated
     */
    public Long getAddUserId() {
        return addUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.addUserId
     *
     * @param addUserId the value for hd_talent.addUserId
     *
     * @mbggenerated
     */
    public void setAddUserId(Long addUserId) {
        this.addUserId = addUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.rank
     *
     * @return the value of hd_talent.rank
     *
     * @mbggenerated
     */
    public String getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.rank
     *
     * @param rank the value for hd_talent.rank
     *
     * @mbggenerated
     */
    public void setRank(String rank) {
        this.rank = rank == null ? null : rank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.addTime
     *
     * @return the value of hd_talent.addTime
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.addTime
     *
     * @param addTime the value for hd_talent.addTime
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.comment
     *
     * @return the value of hd_talent.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.comment
     *
     * @param comment the value for hd_talent.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.email
     *
     * @return the value of hd_talent.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.email
     *
     * @param email the value for hd_talent.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.phone
     *
     * @return the value of hd_talent.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.phone
     *
     * @param phone the value for hd_talent.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.name
     *
     * @return the value of hd_talent.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.name
     *
     * @param name the value for hd_talent.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.jobTitle
     *
     * @return the value of hd_talent.jobTitle
     *
     * @mbggenerated
     */
    public String getJobTitle() {
        return jobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.jobTitle
     *
     * @param jobTitle the value for hd_talent.jobTitle
     *
     * @mbggenerated
     */
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle == null ? null : jobTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.birthYear
     *
     * @return the value of hd_talent.birthYear
     *
     * @mbggenerated
     */
    public Integer getBirthYear() {
        return birthYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.birthYear
     *
     * @param birthYear the value for hd_talent.birthYear
     *
     * @mbggenerated
     */
    public void setBirthYear(Integer birthYear) {
        this.birthYear = birthYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.graduateYear
     *
     * @return the value of hd_talent.graduateYear
     *
     * @mbggenerated
     */
    public Integer getGraduateYear() {
        return graduateYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.graduateYear
     *
     * @param graduateYear the value for hd_talent.graduateYear
     *
     * @mbggenerated
     */
    public void setGraduateYear(Integer graduateYear) {
        this.graduateYear = graduateYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.degreeId
     *
     * @return the value of hd_talent.degreeId
     *
     * @mbggenerated
     */
    public Short getDegreeId() {
        return degreeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.degreeId
     *
     * @param degreeId the value for hd_talent.degreeId
     *
     * @mbggenerated
     */
    public void setDegreeId(Short degreeId) {
        this.degreeId = degreeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.cityId
     *
     * @return the value of hd_talent.cityId
     *
     * @mbggenerated
     */
    public Long getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.cityId
     *
     * @param cityId the value for hd_talent.cityId
     *
     * @mbggenerated
     */
    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.deleted
     *
     * @return the value of hd_talent.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.deleted
     *
     * @param deleted the value for hd_talent.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.status
     *
     * @return the value of hd_talent.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.status
     *
     * @param status the value for hd_talent.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.level
     *
     * @return the value of hd_talent.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.level
     *
     * @param level the value for hd_talent.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.birthday
     *
     * @return the value of hd_talent.birthday
     *
     * @mbggenerated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.birthday
     *
     * @param birthday the value for hd_talent.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.marital_status
     *
     * @return the value of hd_talent.marital_status
     *
     * @mbggenerated
     */
    public Integer getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.marital_status
     *
     * @param maritalStatus the value for hd_talent.marital_status
     *
     * @mbggenerated
     */
    public void setMaritalStatus(Integer maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.id_card
     *
     * @return the value of hd_talent.id_card
     *
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.id_card
     *
     * @param idCard the value for hd_talent.id_card
     *
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.address
     *
     * @return the value of hd_talent.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.address
     *
     * @param address the value for hd_talent.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.expect_annual_salary
     *
     * @return the value of hd_talent.expect_annual_salary
     *
     * @mbggenerated
     */
    public Integer getExpectAnnualSalary() {
        return expectAnnualSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.expect_annual_salary
     *
     * @param expectAnnualSalary the value for hd_talent.expect_annual_salary
     *
     * @mbggenerated
     */
    public void setExpectAnnualSalary(Integer expectAnnualSalary) {
        this.expectAnnualSalary = expectAnnualSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.avatar
     *
     * @return the value of hd_talent.avatar
     *
     * @mbggenerated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.avatar
     *
     * @param avatar the value for hd_talent.avatar
     *
     * @mbggenerated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.english_name
     *
     * @return the value of hd_talent.english_name
     *
     * @mbggenerated
     */
    public String getEnglishName() {
        return englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.english_name
     *
     * @param englishName the value for hd_talent.english_name
     *
     * @mbggenerated
     */
    public void setEnglishName(String englishName) {
        this.englishName = englishName == null ? null : englishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.update_user_id
     *
     * @return the value of hd_talent.update_user_id
     *
     * @mbggenerated
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.update_user_id
     *
     * @param updateUserId the value for hd_talent.update_user_id
     *
     * @mbggenerated
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.city
     *
     * @return the value of hd_talent.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.city
     *
     * @param city the value for hd_talent.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.resume_id
     *
     * @return the value of hd_talent.resume_id
     *
     * @mbggenerated
     */
    public Long getResumeId() {
        return resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.resume_id
     *
     * @param resumeId the value for hd_talent.resume_id
     *
     * @mbggenerated
     */
    public void setResumeId(Long resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.expect_city
     *
     * @return the value of hd_talent.expect_city
     *
     * @mbggenerated
     */
    public String getExpectCity() {
        return expectCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.expect_city
     *
     * @param expectCity the value for hd_talent.expect_city
     *
     * @mbggenerated
     */
    public void setExpectCity(String expectCity) {
        this.expectCity = expectCity == null ? null : expectCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.standardized
     *
     * @return the value of hd_talent.standardized
     *
     * @mbggenerated
     */
    public Integer getStandardized() {
        return standardized;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.standardized
     *
     * @param standardized the value for hd_talent.standardized
     *
     * @mbggenerated
     */
    public void setStandardized(Integer standardized) {
        this.standardized = standardized;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.default_recommand_report_id
     *
     * @return the value of hd_talent.default_recommand_report_id
     *
     * @mbggenerated
     */
    public Long getDefaultRecommandReportId() {
        return defaultRecommandReportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.default_recommand_report_id
     *
     * @param defaultRecommandReportId the value for hd_talent.default_recommand_report_id
     *
     * @mbggenerated
     */
    public void setDefaultRecommandReportId(Long defaultRecommandReportId) {
        this.defaultRecommandReportId = defaultRecommandReportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.post_recommand_report_id
     *
     * @return the value of hd_talent.post_recommand_report_id
     *
     * @mbggenerated
     */
    public Long getPostRecommandReportId() {
        return postRecommandReportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.post_recommand_report_id
     *
     * @param postRecommandReportId the value for hd_talent.post_recommand_report_id
     *
     * @mbggenerated
     */
    public void setPostRecommandReportId(Long postRecommandReportId) {
        this.postRecommandReportId = postRecommandReportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.self_evaluation
     *
     * @return the value of hd_talent.self_evaluation
     *
     * @mbggenerated
     */
    public String getSelfEvaluation() {
        return selfEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.self_evaluation
     *
     * @param selfEvaluation the value for hd_talent.self_evaluation
     *
     * @mbggenerated
     */
    public void setSelfEvaluation(String selfEvaluation) {
        this.selfEvaluation = selfEvaluation == null ? null : selfEvaluation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.salary_desc
     *
     * @return the value of hd_talent.salary_desc
     *
     * @mbggenerated
     */
    public String getSalaryDesc() {
        return salaryDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.salary_desc
     *
     * @param salaryDesc the value for hd_talent.salary_desc
     *
     * @mbggenerated
     */
    public void setSalaryDesc(String salaryDesc) {
        this.salaryDesc = salaryDesc == null ? null : salaryDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.current_salary
     *
     * @return the value of hd_talent.current_salary
     *
     * @mbggenerated
     */
    public Integer getCurrentSalary() {
        return currentSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.current_salary
     *
     * @param currentSalary the value for hd_talent.current_salary
     *
     * @mbggenerated
     */
    public void setCurrentSalary(Integer currentSalary) {
        this.currentSalary = currentSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.current_salary_months
     *
     * @return the value of hd_talent.current_salary_months
     *
     * @mbggenerated
     */
    public Float getCurrentSalaryMonths() {
        return currentSalaryMonths;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.current_salary_months
     *
     * @param currentSalaryMonths the value for hd_talent.current_salary_months
     *
     * @mbggenerated
     */
    public void setCurrentSalaryMonths(Float currentSalaryMonths) {
        this.currentSalaryMonths = currentSalaryMonths;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.expect_salary
     *
     * @return the value of hd_talent.expect_salary
     *
     * @mbggenerated
     */
    public Integer getExpectSalary() {
        return expectSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.expect_salary
     *
     * @param expectSalary the value for hd_talent.expect_salary
     *
     * @mbggenerated
     */
    public void setExpectSalary(Integer expectSalary) {
        this.expectSalary = expectSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.expect_salary_months
     *
     * @return the value of hd_talent.expect_salary_months
     *
     * @mbggenerated
     */
    public Integer getExpectSalaryMonths() {
        return expectSalaryMonths;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.expect_salary_months
     *
     * @param expectSalaryMonths the value for hd_talent.expect_salary_months
     *
     * @mbggenerated
     */
    public void setExpectSalaryMonths(Integer expectSalaryMonths) {
        this.expectSalaryMonths = expectSalaryMonths;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.other_welfare
     *
     * @return the value of hd_talent.other_welfare
     *
     * @mbggenerated
     */
    public String getOtherWelfare() {
        return otherWelfare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.other_welfare
     *
     * @param otherWelfare the value for hd_talent.other_welfare
     *
     * @mbggenerated
     */
    public void setOtherWelfare(String otherWelfare) {
        this.otherWelfare = otherWelfare == null ? null : otherWelfare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.extra_msg
     *
     * @return the value of hd_talent.extra_msg
     *
     * @mbggenerated
     */
    public String getExtraMsg() {
        return extraMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.extra_msg
     *
     * @param extraMsg the value for hd_talent.extra_msg
     *
     * @mbggenerated
     */
    public void setExtraMsg(String extraMsg) {
        this.extraMsg = extraMsg == null ? null : extraMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.apply_job_status
     *
     * @return the value of hd_talent.apply_job_status
     *
     * @mbggenerated
     */
    public Integer getApplyJobStatus() {
        return applyJobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.apply_job_status
     *
     * @param applyJobStatus the value for hd_talent.apply_job_status
     *
     * @mbggenerated
     */
    public void setApplyJobStatus(Integer applyJobStatus) {
        this.applyJobStatus = applyJobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.expect_industry
     *
     * @return the value of hd_talent.expect_industry
     *
     * @mbggenerated
     */
    public String getExpectIndustry() {
        return expectIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.expect_industry
     *
     * @param expectIndustry the value for hd_talent.expect_industry
     *
     * @mbggenerated
     */
    public void setExpectIndustry(String expectIndustry) {
        this.expectIndustry = expectIndustry == null ? null : expectIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.expect_function
     *
     * @return the value of hd_talent.expect_function
     *
     * @mbggenerated
     */
    public String getExpectFunction() {
        return expectFunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.expect_function
     *
     * @param expectFunction the value for hd_talent.expect_function
     *
     * @mbggenerated
     */
    public void setExpectFunction(String expectFunction) {
        this.expectFunction = expectFunction == null ? null : expectFunction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.open_status
     *
     * @return the value of hd_talent.open_status
     *
     * @mbggenerated
     */
    public Integer getOpenStatus() {
        return openStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.open_status
     *
     * @param openStatus the value for hd_talent.open_status
     *
     * @mbggenerated
     */
    public void setOpenStatus(Integer openStatus) {
        this.openStatus = openStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.company_id
     *
     * @return the value of hd_talent.company_id
     *
     * @mbggenerated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.company_id
     *
     * @param companyId the value for hd_talent.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.create_user_id
     *
     * @return the value of hd_talent.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.create_user_id
     *
     * @param createUserId the value for hd_talent.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.old_open_status
     *
     * @return the value of hd_talent.old_open_status
     *
     * @mbggenerated
     */
    public Integer getOldOpenStatus() {
        return oldOpenStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.old_open_status
     *
     * @param oldOpenStatus the value for hd_talent.old_open_status
     *
     * @mbggenerated
     */
    public void setOldOpenStatus(Integer oldOpenStatus) {
        this.oldOpenStatus = oldOpenStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.hh_category_id
     *
     * @return the value of hd_talent.hh_category_id
     *
     * @mbggenerated
     */
    public Long getHhCategoryId() {
        return hhCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.hh_category_id
     *
     * @param hhCategoryId the value for hd_talent.hh_category_id
     *
     * @mbggenerated
     */
    public void setHhCategoryId(Long hhCategoryId) {
        this.hhCategoryId = hhCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.start_work_year
     *
     * @return the value of hd_talent.start_work_year
     *
     * @mbggenerated
     */
    public Integer getStartWorkYear() {
        return startWorkYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.start_work_year
     *
     * @param startWorkYear the value for hd_talent.start_work_year
     *
     * @mbggenerated
     */
    public void setStartWorkYear(Integer startWorkYear) {
        this.startWorkYear = startWorkYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.integrity
     *
     * @return the value of hd_talent.integrity
     *
     * @mbggenerated
     */
    public Integer getIntegrity() {
        return integrity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.integrity
     *
     * @param integrity the value for hd_talent.integrity
     *
     * @mbggenerated
     */
    public void setIntegrity(Integer integrity) {
        this.integrity = integrity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.expect_annual_salary_desc
     *
     * @return the value of hd_talent.expect_annual_salary_desc
     *
     * @mbggenerated
     */
    public String getExpectAnnualSalaryDesc() {
        return expectAnnualSalaryDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.expect_annual_salary_desc
     *
     * @param expectAnnualSalaryDesc the value for hd_talent.expect_annual_salary_desc
     *
     * @mbggenerated
     */
    public void setExpectAnnualSalaryDesc(String expectAnnualSalaryDesc) {
        this.expectAnnualSalaryDesc = expectAnnualSalaryDesc == null ? null : expectAnnualSalaryDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.expect_position_titles
     *
     * @return the value of hd_talent.expect_position_titles
     *
     * @mbggenerated
     */
    public String getExpectPositionTitles() {
        return expectPositionTitles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.expect_position_titles
     *
     * @param expectPositionTitles the value for hd_talent.expect_position_titles
     *
     * @mbggenerated
     */
    public void setExpectPositionTitles(String expectPositionTitles) {
        this.expectPositionTitles = expectPositionTitles == null ? null : expectPositionTitles.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.default_resume_type
     *
     * @return the value of hd_talent.default_resume_type
     *
     * @mbggenerated
     */
    public Integer getDefaultResumeType() {
        return defaultResumeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.default_resume_type
     *
     * @param defaultResumeType the value for hd_talent.default_resume_type
     *
     * @mbggenerated
     */
    public void setDefaultResumeType(Integer defaultResumeType) {
        this.defaultResumeType = defaultResumeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.cv_id
     *
     * @return the value of hd_talent.cv_id
     *
     * @mbggenerated
     */
    public Long getCvId() {
        return cvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.cv_id
     *
     * @param cvId the value for hd_talent.cv_id
     *
     * @mbggenerated
     */
    public void setCvId(Long cvId) {
        this.cvId = cvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.company_name
     *
     * @return the value of hd_talent.company_name
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.company_name
     *
     * @param companyName the value for hd_talent.company_name
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.school
     *
     * @return the value of hd_talent.school
     *
     * @mbggenerated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.school
     *
     * @param school the value for hd_talent.school
     *
     * @mbggenerated
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.jobhunter_id
     *
     * @return the value of hd_talent.jobhunter_id
     *
     * @mbggenerated
     */
    public Long getJobhunterId() {
        return jobhunterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.jobhunter_id
     *
     * @param jobhunterId the value for hd_talent.jobhunter_id
     *
     * @mbggenerated
     */
    public void setJobhunterId(Long jobhunterId) {
        this.jobhunterId = jobhunterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.other_require
     *
     * @return the value of hd_talent.other_require
     *
     * @mbggenerated
     */
    public String getOtherRequire() {
        return otherRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.other_require
     *
     * @param otherRequire the value for hd_talent.other_require
     *
     * @mbggenerated
     */
    public void setOtherRequire(String otherRequire) {
        this.otherRequire = otherRequire == null ? null : otherRequire.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.salary_type
     *
     * @return the value of hd_talent.salary_type
     *
     * @mbggenerated
     */
    public Integer getSalaryType() {
        return salaryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.salary_type
     *
     * @param salaryType the value for hd_talent.salary_type
     *
     * @mbggenerated
     */
    public void setSalaryType(Integer salaryType) {
        this.salaryType = salaryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.cover_by_jobhunter
     *
     * @return the value of hd_talent.cover_by_jobhunter
     *
     * @mbggenerated
     */
    public Integer getCoverByJobhunter() {
        return coverByJobhunter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.cover_by_jobhunter
     *
     * @param coverByJobhunter the value for hd_talent.cover_by_jobhunter
     *
     * @mbggenerated
     */
    public void setCoverByJobhunter(Integer coverByJobhunter) {
        this.coverByJobhunter = coverByJobhunter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.jobhunter_update_time
     *
     * @return the value of hd_talent.jobhunter_update_time
     *
     * @mbggenerated
     */
    public Date getJobhunterUpdateTime() {
        return jobhunterUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.jobhunter_update_time
     *
     * @param jobhunterUpdateTime the value for hd_talent.jobhunter_update_time
     *
     * @mbggenerated
     */
    public void setJobhunterUpdateTime(Date jobhunterUpdateTime) {
        this.jobhunterUpdateTime = jobhunterUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.expert_tagContent
     *
     * @return the value of hd_talent.expert_tagContent
     *
     * @mbggenerated
     */
    public String getExpertTagContent() {
        return expertTagContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.expert_tagContent
     *
     * @param expertTagContent the value for hd_talent.expert_tagContent
     *
     * @mbggenerated
     */
    public void setExpertTagContent(String expertTagContent) {
        this.expertTagContent = expertTagContent == null ? null : expertTagContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.competent_tagContent
     *
     * @return the value of hd_talent.competent_tagContent
     *
     * @mbggenerated
     */
    public String getCompetentTagContent() {
        return competentTagContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.competent_tagContent
     *
     * @param competentTagContent the value for hd_talent.competent_tagContent
     *
     * @mbggenerated
     */
    public void setCompetentTagContent(String competentTagContent) {
        this.competentTagContent = competentTagContent == null ? null : competentTagContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.outside_talent_id
     *
     * @return the value of hd_talent.outside_talent_id
     *
     * @mbggenerated
     */
    public String getOutsideTalentId() {
        return outsideTalentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.outside_talent_id
     *
     * @param outsideTalentId the value for hd_talent.outside_talent_id
     *
     * @mbggenerated
     */
    public void setOutsideTalentId(String outsideTalentId) {
        this.outsideTalentId = outsideTalentId == null ? null : outsideTalentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.source
     *
     * @return the value of hd_talent.source
     *
     * @mbggenerated
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.source
     *
     * @param source the value for hd_talent.source
     *
     * @mbggenerated
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.contact_period
     *
     * @return the value of hd_talent.contact_period
     *
     * @mbggenerated
     */
    public Integer getContactPeriod() {
        return contactPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.contact_period
     *
     * @param contactPeriod the value for hd_talent.contact_period
     *
     * @mbggenerated
     */
    public void setContactPeriod(Integer contactPeriod) {
        this.contactPeriod = contactPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_talent.expect_salary_type
     *
     * @return the value of hd_talent.expect_salary_type
     *
     * @mbggenerated
     */
    public Integer getExpectSalaryType() {
        return expectSalaryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_talent.expect_salary_type
     *
     * @param expectSalaryType the value for hd_talent.expect_salary_type
     *
     * @mbggenerated
     */
    public void setExpectSalaryType(Integer expectSalaryType) {
        this.expectSalaryType = expectSalaryType;
    }
}