package lsc.bean.resume;

import java.io.Serializable;
import java.util.Date;

public class TalentResumeLanguageAbility implements Serializable {
    private Long id;

    private Long resumeId;

    private String languageName;

    private Integer verbal;

    private Integer literacy;

    private String languageLevel;

    private Date createTime;

    private Long createUserId;

    private Date updateTime;

    private Long updateUserId;

    private Boolean defunct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_talent_resume_language_ability
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_language_ability.id
     *
     * @return the value of tb_talent_resume_language_ability.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_language_ability.id
     *
     * @param id the value for tb_talent_resume_language_ability.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_language_ability.resume_id
     *
     * @return the value of tb_talent_resume_language_ability.resume_id
     *
     * @mbggenerated
     */
    public Long getResumeId() {
        return resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_language_ability.resume_id
     *
     * @param resumeId the value for tb_talent_resume_language_ability.resume_id
     *
     * @mbggenerated
     */
    public void setResumeId(Long resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_language_ability.language_name
     *
     * @return the value of tb_talent_resume_language_ability.language_name
     *
     * @mbggenerated
     */
    public String getLanguageName() {
        return languageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_language_ability.language_name
     *
     * @param languageName the value for tb_talent_resume_language_ability.language_name
     *
     * @mbggenerated
     */
    public void setLanguageName(String languageName) {
        this.languageName = languageName == null ? null : languageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_language_ability.verbal
     *
     * @return the value of tb_talent_resume_language_ability.verbal
     *
     * @mbggenerated
     */
    public Integer getVerbal() {
        return verbal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_language_ability.verbal
     *
     * @param verbal the value for tb_talent_resume_language_ability.verbal
     *
     * @mbggenerated
     */
    public void setVerbal(Integer verbal) {
        this.verbal = verbal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_language_ability.literacy
     *
     * @return the value of tb_talent_resume_language_ability.literacy
     *
     * @mbggenerated
     */
    public Integer getLiteracy() {
        return literacy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_language_ability.literacy
     *
     * @param literacy the value for tb_talent_resume_language_ability.literacy
     *
     * @mbggenerated
     */
    public void setLiteracy(Integer literacy) {
        this.literacy = literacy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_language_ability.language_level
     *
     * @return the value of tb_talent_resume_language_ability.language_level
     *
     * @mbggenerated
     */
    public String getLanguageLevel() {
        return languageLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_language_ability.language_level
     *
     * @param languageLevel the value for tb_talent_resume_language_ability.language_level
     *
     * @mbggenerated
     */
    public void setLanguageLevel(String languageLevel) {
        this.languageLevel = languageLevel == null ? null : languageLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_language_ability.create_time
     *
     * @return the value of tb_talent_resume_language_ability.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_language_ability.create_time
     *
     * @param createTime the value for tb_talent_resume_language_ability.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_language_ability.create_user_id
     *
     * @return the value of tb_talent_resume_language_ability.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_language_ability.create_user_id
     *
     * @param createUserId the value for tb_talent_resume_language_ability.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_language_ability.update_time
     *
     * @return the value of tb_talent_resume_language_ability.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_language_ability.update_time
     *
     * @param updateTime the value for tb_talent_resume_language_ability.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_language_ability.update_user_id
     *
     * @return the value of tb_talent_resume_language_ability.update_user_id
     *
     * @mbggenerated
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_language_ability.update_user_id
     *
     * @param updateUserId the value for tb_talent_resume_language_ability.update_user_id
     *
     * @mbggenerated
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_language_ability.defunct
     *
     * @return the value of tb_talent_resume_language_ability.defunct
     *
     * @mbggenerated
     */
    public Boolean getDefunct() {
        return defunct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_language_ability.defunct
     *
     * @param defunct the value for tb_talent_resume_language_ability.defunct
     *
     * @mbggenerated
     */
    public void setDefunct(Boolean defunct) {
        this.defunct = defunct;
    }
}