package lsc.bean.resume;

import java.io.Serializable;
import java.util.Date;

public class TalentResumeProjectExp implements Serializable {
    private Long id;

    private Long resumeId;

    private String startTime;

    private String endTime;

    private String companyName;

    private String projectName;

    private String description;

    private Date createTime;

    private Long createUserId;

    private Date updateTime;

    private Long updateUserId;

    private Boolean defunct;

    private Integer startYear;

    private Integer startMonth;

    private Integer endYear;

    private Integer endMonth;

    private String projectJobTitle;

    private String projectDuty;

    private String timeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_talent_resume_project_exp
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_project_exp.id
     *
     * @return the value of tb_talent_resume_project_exp.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_project_exp.id
     *
     * @param id the value for tb_talent_resume_project_exp.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_project_exp.resume_id
     *
     * @return the value of tb_talent_resume_project_exp.resume_id
     *
     * @mbggenerated
     */
    public Long getResumeId() {
        return resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_project_exp.resume_id
     *
     * @param resumeId the value for tb_talent_resume_project_exp.resume_id
     *
     * @mbggenerated
     */
    public void setResumeId(Long resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_project_exp.start_time
     *
     * @return the value of tb_talent_resume_project_exp.start_time
     *
     * @mbggenerated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_project_exp.start_time
     *
     * @param startTime the value for tb_talent_resume_project_exp.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_project_exp.end_time
     *
     * @return the value of tb_talent_resume_project_exp.end_time
     *
     * @mbggenerated
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_project_exp.end_time
     *
     * @param endTime the value for tb_talent_resume_project_exp.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_project_exp.company_name
     *
     * @return the value of tb_talent_resume_project_exp.company_name
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_project_exp.company_name
     *
     * @param companyName the value for tb_talent_resume_project_exp.company_name
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_project_exp.project_name
     *
     * @return the value of tb_talent_resume_project_exp.project_name
     *
     * @mbggenerated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_project_exp.project_name
     *
     * @param projectName the value for tb_talent_resume_project_exp.project_name
     *
     * @mbggenerated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_project_exp.description
     *
     * @return the value of tb_talent_resume_project_exp.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_project_exp.description
     *
     * @param description the value for tb_talent_resume_project_exp.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_project_exp.create_time
     *
     * @return the value of tb_talent_resume_project_exp.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_project_exp.create_time
     *
     * @param createTime the value for tb_talent_resume_project_exp.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_project_exp.create_user_id
     *
     * @return the value of tb_talent_resume_project_exp.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_project_exp.create_user_id
     *
     * @param createUserId the value for tb_talent_resume_project_exp.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_project_exp.update_time
     *
     * @return the value of tb_talent_resume_project_exp.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_project_exp.update_time
     *
     * @param updateTime the value for tb_talent_resume_project_exp.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_project_exp.update_user_id
     *
     * @return the value of tb_talent_resume_project_exp.update_user_id
     *
     * @mbggenerated
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_project_exp.update_user_id
     *
     * @param updateUserId the value for tb_talent_resume_project_exp.update_user_id
     *
     * @mbggenerated
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_project_exp.defunct
     *
     * @return the value of tb_talent_resume_project_exp.defunct
     *
     * @mbggenerated
     */
    public Boolean getDefunct() {
        return defunct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_project_exp.defunct
     *
     * @param defunct the value for tb_talent_resume_project_exp.defunct
     *
     * @mbggenerated
     */
    public void setDefunct(Boolean defunct) {
        this.defunct = defunct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_project_exp.start_year
     *
     * @return the value of tb_talent_resume_project_exp.start_year
     *
     * @mbggenerated
     */
    public Integer getStartYear() {
        return startYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_project_exp.start_year
     *
     * @param startYear the value for tb_talent_resume_project_exp.start_year
     *
     * @mbggenerated
     */
    public void setStartYear(Integer startYear) {
        this.startYear = startYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_project_exp.start_month
     *
     * @return the value of tb_talent_resume_project_exp.start_month
     *
     * @mbggenerated
     */
    public Integer getStartMonth() {
        return startMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_project_exp.start_month
     *
     * @param startMonth the value for tb_talent_resume_project_exp.start_month
     *
     * @mbggenerated
     */
    public void setStartMonth(Integer startMonth) {
        this.startMonth = startMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_project_exp.end_year
     *
     * @return the value of tb_talent_resume_project_exp.end_year
     *
     * @mbggenerated
     */
    public Integer getEndYear() {
        return endYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_project_exp.end_year
     *
     * @param endYear the value for tb_talent_resume_project_exp.end_year
     *
     * @mbggenerated
     */
    public void setEndYear(Integer endYear) {
        this.endYear = endYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_project_exp.end_month
     *
     * @return the value of tb_talent_resume_project_exp.end_month
     *
     * @mbggenerated
     */
    public Integer getEndMonth() {
        return endMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_project_exp.end_month
     *
     * @param endMonth the value for tb_talent_resume_project_exp.end_month
     *
     * @mbggenerated
     */
    public void setEndMonth(Integer endMonth) {
        this.endMonth = endMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_project_exp.project_job_title
     *
     * @return the value of tb_talent_resume_project_exp.project_job_title
     *
     * @mbggenerated
     */
    public String getProjectJobTitle() {
        return projectJobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_project_exp.project_job_title
     *
     * @param projectJobTitle the value for tb_talent_resume_project_exp.project_job_title
     *
     * @mbggenerated
     */
    public void setProjectJobTitle(String projectJobTitle) {
        this.projectJobTitle = projectJobTitle == null ? null : projectJobTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_project_exp.project_duty
     *
     * @return the value of tb_talent_resume_project_exp.project_duty
     *
     * @mbggenerated
     */
    public String getProjectDuty() {
        return projectDuty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_project_exp.project_duty
     *
     * @param projectDuty the value for tb_talent_resume_project_exp.project_duty
     *
     * @mbggenerated
     */
    public void setProjectDuty(String projectDuty) {
        this.projectDuty = projectDuty == null ? null : projectDuty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_project_exp.time_desc
     *
     * @return the value of tb_talent_resume_project_exp.time_desc
     *
     * @mbggenerated
     */
    public String getTimeDesc() {
        return timeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_project_exp.time_desc
     *
     * @param timeDesc the value for tb_talent_resume_project_exp.time_desc
     *
     * @mbggenerated
     */
    public void setTimeDesc(String timeDesc) {
        this.timeDesc = timeDesc == null ? null : timeDesc.trim();
    }
}