package lsc.bean.resume;

import java.io.Serializable;
import java.util.Date;

public class TalentResumeCertification implements Serializable {
    private Long id;

    private Long resumeId;

    private String cerName;

    private Integer issuedYear;

    private Integer issuedMonth;

    private String description;

    private Date createTime;

    private Long createUserId;

    private Date updateTime;

    private Long updateUserId;

    private Boolean defunct;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * tb_talent_resume_certification
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tb_talent_resume_certification.id
     *
     * @return the value of tb_talent_resume_certification.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tb_talent_resume_certification.id
     *
     * @param id the value for tb_talent_resume_certification.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tb_talent_resume_certification.resume_id
     *
     * @return the value of tb_talent_resume_certification.resume_id
     *
     * @mbggenerated
     */
    public Long getResumeId() {
        return resumeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tb_talent_resume_certification.resume_id
     *
     * @param resumeId the value for tb_talent_resume_certification.resume_id
     *
     * @mbggenerated
     */
    public void setResumeId(Long resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tb_talent_resume_certification.cer_name
     *
     * @return the value of tb_talent_resume_certification.cer_name
     *
     * @mbggenerated
     */
    public String getCerName() {
        return cerName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tb_talent_resume_certification.cer_name
     *
     * @param cerName the value for tb_talent_resume_certification.cer_name
     *
     * @mbggenerated
     */
    public void setCerName(String cerName) {
        this.cerName = cerName == null ? null : cerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tb_talent_resume_certification.issued_year
     *
     * @return the value of tb_talent_resume_certification.issued_year
     *
     * @mbggenerated
     */
    public Integer getIssuedYear() {
        return issuedYear;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tb_talent_resume_certification.issued_year
     *
     * @param issuedYear the value for tb_talent_resume_certification.issued_year
     *
     * @mbggenerated
     */
    public void setIssuedYear(Integer issuedYear) {
        this.issuedYear = issuedYear;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tb_talent_resume_certification.issued_month
     *
     * @return the value of tb_talent_resume_certification.issued_month
     *
     * @mbggenerated
     */
    public Integer getIssuedMonth() {
        return issuedMonth;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tb_talent_resume_certification.issued_month
     *
     * @param issuedMonth the value for tb_talent_resume_certification.issued_month
     *
     * @mbggenerated
     */
    public void setIssuedMonth(Integer issuedMonth) {
        this.issuedMonth = issuedMonth;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tb_talent_resume_certification.description
     *
     * @return the value of tb_talent_resume_certification.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tb_talent_resume_certification.description
     *
     * @param description the value for tb_talent_resume_certification.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tb_talent_resume_certification.create_time
     *
     * @return the value of tb_talent_resume_certification.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tb_talent_resume_certification.create_time
     *
     * @param createTime the value for tb_talent_resume_certification.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tb_talent_resume_certification.create_user_id
     *
     * @return the value of tb_talent_resume_certification.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tb_talent_resume_certification.create_user_id
     *
     * @param createUserId the value for tb_talent_resume_certification.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tb_talent_resume_certification.update_time
     *
     * @return the value of tb_talent_resume_certification.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tb_talent_resume_certification.update_time
     *
     * @param updateTime the value for tb_talent_resume_certification.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tb_talent_resume_certification.update_user_id
     *
     * @return the value of tb_talent_resume_certification.update_user_id
     *
     * @mbggenerated
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tb_talent_resume_certification.update_user_id
     *
     * @param updateUserId the value for tb_talent_resume_certification.update_user_id
     *
     * @mbggenerated
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tb_talent_resume_certification.defunct
     *
     * @return the value of tb_talent_resume_certification.defunct
     *
     * @mbggenerated
     */
    public Boolean getDefunct() {
        return defunct;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tb_talent_resume_certification.defunct
     *
     * @param defunct the value for tb_talent_resume_certification.defunct
     *
     * @mbggenerated
     */
    public void setDefunct(Boolean defunct) {
        this.defunct = defunct;
    }
}