package lsc.bean.resume;

import java.io.Serializable;
import java.util.Date;

public class TalentResumeEduExp implements Serializable {
    private Long id;

    private Long resumeId;

    private String startTime;

    private String endTime;

    private String school;

    private String schoolLogo;

    private String profession;

    private Integer degreeId;

    private String degree;

    private Date createTime;

    private Long createUserId;

    private Date updateTime;

    private Long updateUserId;

    private Boolean defunct;

    private Integer startYear;

    private Integer startMonth;

    private Integer endYear;

    private Integer endMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_talent_resume_edu_exp
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_edu_exp.id
     *
     * @return the value of tb_talent_resume_edu_exp.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_edu_exp.id
     *
     * @param id the value for tb_talent_resume_edu_exp.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_edu_exp.resume_id
     *
     * @return the value of tb_talent_resume_edu_exp.resume_id
     *
     * @mbggenerated
     */
    public Long getResumeId() {
        return resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_edu_exp.resume_id
     *
     * @param resumeId the value for tb_talent_resume_edu_exp.resume_id
     *
     * @mbggenerated
     */
    public void setResumeId(Long resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_edu_exp.start_time
     *
     * @return the value of tb_talent_resume_edu_exp.start_time
     *
     * @mbggenerated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_edu_exp.start_time
     *
     * @param startTime the value for tb_talent_resume_edu_exp.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_edu_exp.end_time
     *
     * @return the value of tb_talent_resume_edu_exp.end_time
     *
     * @mbggenerated
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_edu_exp.end_time
     *
     * @param endTime the value for tb_talent_resume_edu_exp.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_edu_exp.school
     *
     * @return the value of tb_talent_resume_edu_exp.school
     *
     * @mbggenerated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_edu_exp.school
     *
     * @param school the value for tb_talent_resume_edu_exp.school
     *
     * @mbggenerated
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_edu_exp.school_logo
     *
     * @return the value of tb_talent_resume_edu_exp.school_logo
     *
     * @mbggenerated
     */
    public String getSchoolLogo() {
        return schoolLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_edu_exp.school_logo
     *
     * @param schoolLogo the value for tb_talent_resume_edu_exp.school_logo
     *
     * @mbggenerated
     */
    public void setSchoolLogo(String schoolLogo) {
        this.schoolLogo = schoolLogo == null ? null : schoolLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_edu_exp.profession
     *
     * @return the value of tb_talent_resume_edu_exp.profession
     *
     * @mbggenerated
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_edu_exp.profession
     *
     * @param profession the value for tb_talent_resume_edu_exp.profession
     *
     * @mbggenerated
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_edu_exp.degree_id
     *
     * @return the value of tb_talent_resume_edu_exp.degree_id
     *
     * @mbggenerated
     */
    public Integer getDegreeId() {
        return degreeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_edu_exp.degree_id
     *
     * @param degreeId the value for tb_talent_resume_edu_exp.degree_id
     *
     * @mbggenerated
     */
    public void setDegreeId(Integer degreeId) {
        this.degreeId = degreeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_edu_exp.degree
     *
     * @return the value of tb_talent_resume_edu_exp.degree
     *
     * @mbggenerated
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_edu_exp.degree
     *
     * @param degree the value for tb_talent_resume_edu_exp.degree
     *
     * @mbggenerated
     */
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_edu_exp.create_time
     *
     * @return the value of tb_talent_resume_edu_exp.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_edu_exp.create_time
     *
     * @param createTime the value for tb_talent_resume_edu_exp.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_edu_exp.create_user_id
     *
     * @return the value of tb_talent_resume_edu_exp.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_edu_exp.create_user_id
     *
     * @param createUserId the value for tb_talent_resume_edu_exp.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_edu_exp.update_time
     *
     * @return the value of tb_talent_resume_edu_exp.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_edu_exp.update_time
     *
     * @param updateTime the value for tb_talent_resume_edu_exp.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_edu_exp.update_user_id
     *
     * @return the value of tb_talent_resume_edu_exp.update_user_id
     *
     * @mbggenerated
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_edu_exp.update_user_id
     *
     * @param updateUserId the value for tb_talent_resume_edu_exp.update_user_id
     *
     * @mbggenerated
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_edu_exp.defunct
     *
     * @return the value of tb_talent_resume_edu_exp.defunct
     *
     * @mbggenerated
     */
    public Boolean getDefunct() {
        return defunct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_edu_exp.defunct
     *
     * @param defunct the value for tb_talent_resume_edu_exp.defunct
     *
     * @mbggenerated
     */
    public void setDefunct(Boolean defunct) {
        this.defunct = defunct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_edu_exp.start_year
     *
     * @return the value of tb_talent_resume_edu_exp.start_year
     *
     * @mbggenerated
     */
    public Integer getStartYear() {
        return startYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_edu_exp.start_year
     *
     * @param startYear the value for tb_talent_resume_edu_exp.start_year
     *
     * @mbggenerated
     */
    public void setStartYear(Integer startYear) {
        this.startYear = startYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_edu_exp.start_month
     *
     * @return the value of tb_talent_resume_edu_exp.start_month
     *
     * @mbggenerated
     */
    public Integer getStartMonth() {
        return startMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_edu_exp.start_month
     *
     * @param startMonth the value for tb_talent_resume_edu_exp.start_month
     *
     * @mbggenerated
     */
    public void setStartMonth(Integer startMonth) {
        this.startMonth = startMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_edu_exp.end_year
     *
     * @return the value of tb_talent_resume_edu_exp.end_year
     *
     * @mbggenerated
     */
    public Integer getEndYear() {
        return endYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_edu_exp.end_year
     *
     * @param endYear the value for tb_talent_resume_edu_exp.end_year
     *
     * @mbggenerated
     */
    public void setEndYear(Integer endYear) {
        this.endYear = endYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_talent_resume_edu_exp.end_month
     *
     * @return the value of tb_talent_resume_edu_exp.end_month
     *
     * @mbggenerated
     */
    public Integer getEndMonth() {
        return endMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_talent_resume_edu_exp.end_month
     *
     * @param endMonth the value for tb_talent_resume_edu_exp.end_month
     *
     * @mbggenerated
     */
    public void setEndMonth(Integer endMonth) {
        this.endMonth = endMonth;
    }
}